<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>wwj-club</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>mc-common</module>
        <module>mc-manage</module>
        <module>mc-monitor</module>
        <module>mc-web</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!--锁定版本-->
        <junit.version>4.13.2</junit.version>
        <lombok.version>1.18.24</lombok.version>
        <hutool-all.version>5.8.25</hutool-all.version>
        <springboot.version>3.2.5</springboot.version>
        <mysql-connector-j.version>8.2.0</mysql-connector-j.version>
        <easyexcel.version>3.3.4</easyexcel.version>
        <minio.version>3.0.10</minio.version>
        <hibernate-validator.version>8.0.1.Final</hibernate-validator.version>
        <jjwt.version>0.9.1</jjwt.version>
        <jaxb-api.version>2.3.1</jaxb-api.version>
        <mybatis-spring-boot-starter.version>3.0.4</mybatis-spring-boot-starter.version>
        <pagehelper-spring-boot-starter.version>1.4.7</pagehelper-spring-boot-starter.version>
        <spring-boot-admin-starter-client.version>3.1.5</spring-boot-admin-starter-client.version>
        <spring-boot-admin-server.version>3.1.5</spring-boot-admin-server.version>
        <spring-boot-admin-server-ui.version>3.1.5</spring-boot-admin-server-ui.version>
        <okhttp.version>4.12.0</okhttp.version>
        <knife4j-openapi3-jakarta-spring-boot-starter.version>4.4.0
        </knife4j-openapi3-jakarta-spring-boot-starter.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!--spring-boot-starter-parent-->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>${springboot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <!--junit-->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <!--lombok-->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
        <!--hutool-all-->
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>${hutool-all.version}</version>
        </dependency>
        <!--spring-boot-starter-web-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!--spring-boot-starter-test-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>
    </dependencies>



</project>